version: '3'
services:
  backend:
    build:
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - real-world-network

  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    networks:
      - real-world-network

networks:
  real-world-network:
    driver: bridge
