version: '3'
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - real-world-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - real-world-network

  cypress:
    build:
      context: ./frontend/cypress
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    environment:
      - CYPRESS_BASE_URL=http://frontend
    volumes:
      - ./frontend:/e2e
    networks:
      - real-world-network


networks:
  real-world-network:
    driver: bridge
