name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo setting up!


  call-deploy-backend:
    if: github.event_name == 'pull_request'
    needs: [Setup]
    uses: ./.github/workflows/deploy-backend.yml
    with:
        environment: development
        AWS_REGION: ${{ vars.AWS_REGION }}
    secrets:
        AWS_GITHUB_ACCESS_ROLE: ${{ secrets.AWS_GITHUB_ACCESS_ROLE }}
