name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# concurrency required to avoid terraform lock contention during ECR provisioning
concurrency: cicd-${{ github.repository }}-pipeline

jobs:

  Start:
    runs-on: ubuntu-latest
    steps:
      - name: Start Message
        run: echo Starting pipeline!


  deploy-dev:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: pwd
        run: pwd

      - name: Call deploy workflow for dev
        uses: ./.github/workflows/deploy.yml
        with:
          environment: 'development'

  deploy-testing:
    runs-on: ubuntu-latest
    environment: testing
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Call deploy workflow for test
        uses: ./.github/workflows/deploy.yml
        with:
          environment: 'testing'

  deploy-qa:
    runs-on: ubuntu-latest
    environment: qa
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Call deploy workflow for qa
        uses: ./.github/workflows/deploy.yml
        with:
          environment: 'qa'
