name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# concurrency required to avoid terraform lock contention during ECR provisioning
concurrency: cicd-${{ github.repository }}-pipeline

jobs:

  deploy:
    # NOTE: No name
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          [development, testing, qa]

    # NOTE: No permissions
    # NOTE: No outputs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log Environment Variable
        run: |
          echo "Environment: $ENVIRONMENT"
        env:
          ENVIRONMENT: ${{ matrix.environment }}
          #DEV_SECRET: ${{ secrets.DEV_SECRET }}
          #TESTING_SECRET: ${{ secrets.TESTING_SECRET }}
          #QA_SECRET: ${{ secrets.QA_SECRET }}
