name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# concurrency required to avoid terraform lock contention during ECR provisioning
concurrency: cicd-${{ github.repository }}-pipeline

jobs:

  Start:
    runs-on: ubuntu-latest
    steps:
      - name: Start Message
        run: echo Starting pipeline!


  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'development'


  deploy-testing:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'testing'

  deploy-qa:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'qa'
