name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo setting up!
          

  BackendDevDeploy:
    name: Deploy Backend to Dev Env
    if: github.event_name == 'pull_request'
    needs: [Setup]
    runs-on: ubuntu-latest
    environment:
        name: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up QEMU for arm64
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        if: runner.os == 'Linux'
          
      - name: Set up Docker for arm64
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64
          
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - name: Build and push Docker image
        run: |
          cd frontend
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/arm64 -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_BACKEND_IMAGE:latest --push .

      
  FrontendDevDeploy:
    name: Deploy Frontend to Dev Env
    if: github.event_name == 'pull_request'
    needs: [BackendDevDeploy]
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Placeholder
        run: echo I am deploying!

    
  BackendTestDeploy:
    name: Deploy Backend to Test Env
    if: github.event.ref == 'refs/heads/master'
    needs: [Setup]
    runs-on: ubuntu-latest
    environment:
        name: testing
    steps:
        - name: Placeholder
          run: echo I am deploying!

  FrontendTestDeploy:
    name: Deploy to Test Env
    if: github.event.ref == 'refs/heads/master'
    needs: [BackendTestDeploy]
    runs-on: ubuntu-latest
    environment:
      name: testing
    steps:
      - name: Placeholder
        run: echo I am deploying!


  BackendQADeploy:
    name: Deploy Backend to QA Env
    needs: [FrontendTestDeploy]
    runs-on: ubuntu-latest
    environment:
      name: QA
    steps:
      - name: Placeholder
        run: echo I am deploying!


  FrontendQADeploy:
    name: Deploy Backend to QA Env
    needs: [FrontendTestDeploy]
    runs-on: ubuntu-latest
    environment:
      name: QA
    steps:
      - name: Placeholder
        run: echo I am deploying!
