name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# concurrency required to avoid terraform lock contention during ECR provisioning
concurrency: cicd-${{ github.repository }}-pipeline

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo setting up!
          

  BackendDevDeploy:
    name: Deploy Backend to Dev Env
    if: github.event_name == 'pull_request'
    needs: [Setup]
    runs-on: ubuntu-latest

    environment:
      name: development

    permissions:
      id-token: write
      contents: read

    outputs:
      image_tag: ${{ steps.build-publish.outputs.image_tag }} #change
      full_image: ${{ steps.build-publish.outputs.full_image }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACCESS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: GitHub-OIDC-Terraform


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false


      - name: prepare ECR repo name based on the Github repository
        shell: bash
        run: |
          set -eux
          # lowercase the name
          repo="${GITHUB_REPOSITORY,,}"
  
          # replace / with _
          echo "ECR_REPO_NAME=${repo//\//_}" >> $GITHUB_ENV


      - name: Create S3 Bucket if it doesn't exist
        shell: bash
        run: |
          set -eux
          BUCKET_NAME=${{ vars.BACKEND_S3_BUCKET }}
          REGION=${{ vars.AWS_REGION }}
          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2&gt;/dev/null; then
            aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$REGION" --create-bucket-configuration LocationConstraint="$REGION"
            echo "Bucket $BUCKET_NAME created in $REGION"
          else
            echo "Bucket $BUCKET_NAME already exists"
          fi


      - name: TF init
        shell: bash
        run: |
          set -eux
          terraform init -upgrade -reconfigure \
            -backend-config='skip_metadata_api_check=true' \
            -backend-config='skip_region_validation=true' \
            -backend-config='skip_credentials_validation=true' \
            -backend-config='region=${{ vars.AWS_REGION }}' \
            -backend-config='bucket=${{ vars.BACKEND_S3_BUCKET }}' \
            -backend-config='key=docker-ecr/terraform-${{ vars.BACKEND_ECR_REPO_NAME }}.tfstate' \
            -backend-config='dynamodb_table=${{ vars.BACKEND_DYNAMODB_TABLE }}' \
            -backend-config='role_arn=${{ secrets.AWS_BACKEND_ACCESS_ROLE }}'
        working-directory: ./infrastructure


      - name: Debug Directory Contents # TBR
        run: |
          ls -la ${{ github.action_path }}
        working-directory: ./infrastructure


      - name: TF apply (Create ECR repo)
        shell: bash
        run: |
          set -eux
          terraform apply \
            -var 'repository_name=${{ vars.BACKEND_ECR_REPO_NAME }}' \
            -var 'lifecycle_policy=./policy.json' \
            -var 'iam_role=${{ secrets.AWS_BACKEND_ACCESS_ROLE }}' \
            -var 'aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}' \
            -auto-approve
        working-directory: ./infrastructure


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}
          mask-password: "true" # see: https://github.com/aws-actions/amazon-ecr-login#docker-credentials
  

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.BACKEND_ECR_REPO_NAME }}
          IMAGE_TAG: ${{ vars.BACKEND_IMAGE_TAG }}
        run: |
          docker build "./api" -f "./api/Dockerfile" -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG" 
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      
  FrontendDevDeploy:
    name: Deploy Frontend to Dev Env
    if: github.event_name == 'pull_request'
    needs: [Setup]
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Placeholder
        run: echo I am deploying!

    
  BackendTestDeploy:
    name: Deploy Backend to Test Env
    if: github.event.ref == 'refs/heads/master'
    needs: [Setup]
    runs-on: ubuntu-latest
    environment:
        name: testing
    steps:
        - name: Placeholder
          run: echo I am deploying!

  FrontendTestDeploy:
    name: Deploy Frontend to Test Env
    if: github.event.ref == 'refs/heads/master'
    needs: [Setup]
    runs-on: ubuntu-latest
    environment:
      name: testing
    steps:
      - name: Placeholder
        run: echo I am deploying!


  BackendQADeploy:
    name: Deploy Backend to QA Env
    needs: [FrontendTestDeploy, BackendTestDeploy]
    runs-on: ubuntu-latest
    environment:
      name: QA
    steps:
      - name: Placeholder
        run: echo I am deploying!


  FrontendQADeploy:
    name: Deploy Backend to QA Env
    needs: [FrontendTestDeploy, BackendTestDeploy]
    runs-on: ubuntu-latest
    environment:
      name: QA
    steps:
      - name: Placeholder
        run: echo I am deploying!
