name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# concurrency required to avoid terraform lock contention during ECR provisioning
concurrency: cicd-${{ github.repository }}-pipeline

jobs:

  Start:
    runs-on: ubuntu-latest
    steps:
      - name: Start Message
        run: echo Starting pipeline!


  deploy-dev:
    # NOTE: No name
    if: github.event_name == 'pull_request'
    needs: [Start]
    # NOTE: No environment
    # NOTE: No permissions
    # NOTE: No outputs
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
      AWS_REGION: ${{ vars.AWS_REGION }}


  deploy-testing:
    # NOTE: No name
    if: github.event.ref == 'refs/heads/master'
    needs: [Start]
    # NOTE: No environment
    # NOTE: No permissions
    # NOTE: No outputs
    uses: ./.github/workflows/deploy.yml
    with:
      environment: testing
      AWS_REGION: ${{ vars.AWS_REGION }}


  deploy-qa:
    # NOTE: No name
    needs: [deploy-testing]
    # NOTE: No environment
    # NOTE: No permissions
    # NOTE: No outputs
    uses: ./.github/workflows/deploy.yml
    with:
      environment: qa
      AWS_REGION: ${{ vars.AWS_REGION }}
