name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
        name: ${{ inputs.environment }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

        # TO BE REMOVED
      - name: Deploy to ${{ inputs.environment }}
        run: echo environment input string is ${{ inputs.environment }}

      - name: Log environment details
        run: |
          echo "Environment Variables:"
          printenv
