name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
        name: ${{ inputs.environment }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log AWS_REGION
        run: |
          echo "AWS_REGION for ${{ inputs.environment }} is $AWS_REGION"
