name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      BACKEND_DYNAMODB_TABLE:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
        name: ${{ inputs.environment }}
    steps:

      - name: Log BACKEND_DYNAMODB_TABLE
        run: |
          echo "BACKEND_DYNAMODB_TABLE for ${{ inputs.environment }} is ${{ inputs.BACKEND_DYNAMODB_TABLE }}"
