---
    name: PyTest Tests
    
    on:
      push:
        branches:
          master
      pull_request:
      workflow_dispatch:
    
    jobs:
      tests:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        environment: development
        env:
          DB_CONN_STR: ${{ vars.DB_CONN_STR }}
          DB_BUCKET_NAME: ${{ vars.DB_BUCKET_NAME }}
          DB_SCOPE_NAME: ${{ vars.DB_SCOPE_NAME }}
          DB_USERNAME: ${{ vars.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    
        steps:
          - uses: actions/checkout@v1
            with:
              submodules: recursive
          - name: Set up Python and requirements
            run: |
              sudo apt -y update
              sudo apt -y install python3-pip python3-testresources
              python -m pip install -r requirements.txt
          - name: Run tests
            timeout-minutes: 5
            run: ./scripts/pytest-test.sh
