---
name: Realworld Tests

on:
  push:
    branches:
      master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1"

jobs:
  realworld-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: development
    env:
      DB_CONN_STR: ${{ vars.DB_CONN_STR }}
      DB_BUCKET_NAME: ${{ vars.DB_BUCKET_NAME }}
      DB_SCOPE_NAME: ${{ vars.DB_SCOPE_NAME }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Set up Python and requirements
        run: |
          sudo apt -y update
          sudo apt -y install python3-pip python3-testresources
          python -m pip install -r api/requirements.txt
      - name: Start the FastAPI server
        run: |
          ./scripts/start-api.sh &
          # Wait for the server
          while ! curl "http://localhost:8000/health" > /dev/null 2>&1
          do
            sleep 1;
          done
          echo "Server ready."
      - name: Run realworld backend tests
        run: ./scripts/realworld-test.sh
        env:
          APIURL: http://localhost:8000
