name: Destroy Infrastructure

on:
  workflow_dispatch:


# concurrency required to avoid terraform lock contention during ECR provisioning
concurrency: cicd-${{ github.repository }}-pipeline


jobs:
  Setup:
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder
        run: echo setting up!


    # TO BE IMPLEMENTED